### ISSUE TITLE
Implement MEI Algorithm

### ISSUE THREAD

**Issue by milsen** [ogdf/ogdf#135]
In GitLab by @TiloW on Nov 7, 2016, 08:58

Implement the algorithms that optimally insert a set of edges into a planar graph described in 

> M. Chimani, P. Hliněný. [Inserting Multiple Edges into a Planar Graph](http://www-lehre.informatik.uni-osnabrueck.de/theoinf/lib/exe/fetch.php/pubs/socg16_preprint_exactmei.pdf). 32nd International Symposium on Computational Geometry (SoCG) 2016, Boston, MA, USA, LIPIcs, to appear.

#### TODO: r-MEI
 * [x] Star insertion with globally shortest paths
 * [x] Triangulation with locally shortest paths
 * [x] TSequence crossing query
 * [x] Auxiliary structures for faster crossing queries
 * [x] Count crossings between Trinet and TSequence
 * [ ] Basic Branch-and-Bound
 * [x] Preprocessing for B&B A*: Compute shortest paths between any node and all trinodes
 * [ ] ~~Preprocessing for B&B A*: Compute costs for tricell traversal (?)~~
